### ISSUE TITLE
The code of SCS metrics

### ISSUE THREAD

**Issue by Daisy-7** [aysim/dynnet#1]
Hi ! It's a nice work for semantic change detection in long time series images.  
In the paper of DynamicEarthNet, you proposed a new metrics for evaluate the performace of semantic change segmentation. However, I didn't find the code of SCS metrics in this project. 

Could you please release the code of the SCS metrics? While we can upload our results to codalab to get the final score,  it's more convenient to validate the model locally before we test it on validation and test set.

Anyway，thank you for releasing the dataset and code！

**Comment by aysim** [comment]
Hi! thanks! I pushed the semantic change segmentation code -- same as in the codalab evaluation.
