### ISSUE TITLE
The bands of Planet imagery

### ISSUE THREAD

**Issue by MartinPernus** [aysim/dynnet#6]
Hi! Thank you for your wonderful work.

I am trying to understand the band content of DEN Planet imagery. When reading with rasterio library, an individual file consists of 9 bands. This is confusing to me since the PlanetScope imagery [should consist of 8 bands](https://developers.planet.com/docs/apis/data/sensors/). Could you elaborate?

**Comment by aysim** [comment]
Hello! Thanks :)

We provide a fusion monitoring product from Planet Labs, equipped with four channels (RGB + NIR). I'm uncertain about the data you're referring to that includes nine bands. Could you please provide more details?

**Comment by MartinPernus** [comment]
Hey,

An example folder `planet/54N/22E-198N/7312_3008_13`consists of two folders, `PF-QA` and `PF-SR`, where each directory contains TIF files with 9 bands and 4 bands, respectively. What is the data with 9 channels?

**Comment by aysim** [comment]
Sorry for the confusion, as indicated by the training/test splits, the image data (4-channels) is the surface reflectance product (PF-SR). PF-QA, the planet's quality assurance product, consists of 9 channels indicating the raw and gap-filled portions of the data. You can find more information in our [supplementary material](https://openaccess.thecvf.com/content/CVPR2022/supplemental/Toker_DynamicEarthNet_Daily_Multi-Spectral_CVPR_2022_supplemental.pdf) or in the product's [technical specification](https://assets.planet.com/docs/Planet_fusion_specification_March_2021.pdf).

**Comment by MartinPernus** [comment]
Thank you!!
